name: docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-ubuntu:
    name: "docs on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jaxlib jax
          sudo apt install -y pandoc
          python -m pip install --upgrade pip
          pip install .
          pip install -r docs/requirements.txt
          export SEPES_TEST_ARRAYLIB=jax
          export SEPES_BACKEND=jax
          export XLA_FLAGS=--xla_force_host_platform_device_count=8
      - name: Test doctests
        run: |
          cd docs
          make doctest
      - name: Test docs to HTML
        run: |
          cd docs
          make html
